// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmntatefvgabphifgfac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtbnRhdGVmdmdhYnBoaWZnZmFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTIzMDcsImV4cCI6MjA2ODA2ODMwN30.1N8IIPv0qnsWRcrZV3h-WeE3FyDt34qkkqraRi_XKNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});