// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txlqvhdyrgeqkrfnvkyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4bHF2aGR5cmdlcWtyZm52a3l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NzUxOTcsImV4cCI6MjA2NzQ1MTE5N30.M6PFZSoN0pGtTkng9FJGkqEW-24cP-1gVZ2bukVs7rI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});